package:
  name: "ras2d_viz"
  version: "0.1.0"

source:
  # Relative path to the parent directory.
  path: ..

requirements:
  host:
    - python
    - setuptools
  build:
    - python {{ python }}
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    # - dependencyPackage1
    # - dependencyPackage2
    # ...

about:
  home: https://github.com/Clovin4/ras2d_viz
  license: MIT license
  license_familY: MIT license
  license_file: LICENSE
  summary: "This package makes your wildest dreams come true"

extra:
  recipe-maintainers:
    - Clovin4